services:
  memberkitsync:
    build:
      context: ./memberkitsync
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - internal_supabase
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: "3001"
    networks:
      - internal_supabase
    depends_on:
      - memberkitsync
    restart: unless-stopped

networks:
  internal_supabase:
    driver: bridge
